apiVersion: v1
kind: ConfigMap
metadata:
  name: smartcart-config
  namespace: smartcart
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/smartcartdb
  SPRING_DATA_REDIS_HOST: redis-service
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  JWT_EXPIRATION: "86400000"
  SERVER_PORT: "8080"
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
