apiVersion: v1
kind: Secret
metadata:
  name: smartcart-secret
  namespace: smartcart
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: smartcart
  SPRING_DATASOURCE_PASSWORD: smartcart123
  POSTGRES_DB: smartcartdb
  POSTGRES_USER: smartcart
  POSTGRES_PASSWORD: smartcart123
  JWT_SECRET: smartcartSecretKey2024VeryLongSecretKeyForHMACSHA256Algorithm
